Future #50 implements recipe register
Aso2101122/bugbug pull request #57
Opened 2022-11-30 01:42 UTC by Aso2001025

## チケット(issue)へのリンク

* https://github.com/Aso2101122/bugbug/issues/50

## やったこと

*  レシピ投稿の入力画面作成
* レシピテーブルへの保存
* タグテーブルへの保存
* レシピタグテーブルへの保存
* 材料の保存
* 手順の保存

## やってないこと(未実装部分)

* タグの表示
* バリデーション

## できるようになること（ユーザ目線）

* レシピの登録

## 動作確認

* 正しい値を入力　成功
* 新しいタグの入力　タグの登録から始まる
* 材料欄に空白を入れる　空白行は保存されない
* 手順に空白を入れる　画像がない場合は保存　作り方がない場合は保存されない
* その他の部分の空白　保存される

## その他

* 懸念点や注意点などがあれば記載

2022-11-30 13:50 UTC, Aso2101122 requested changes
結構細かいところみたからちょっとした修正が多いけど修正よろしくお願いします。（重要なところ以外は誰かに任せてもいいよ）
また、不明瞭なところは口頭かこのレビューにリプライを送ってください

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/form/RecipeRegisterForm.java
> +	private List<MultipartFile> datail_images;
detail（詳細）ではなく手順画像という意味の単語に修正お願いします。

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/form/RecipeRegisterForm.java
> +	private String explan;
エンティティにも書いたけど説明文のフィールド名の変更お願いします。

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/service/TagServiceImpl.java
> +    //IDの取得
メソッド名とコメントは他にも純粋にタグを取得するだけのときがあるから、
「タグが存在するときは取得、存在しないときは保存」みたいな意味合いのメソッド名とコメントがいいかも

2022-11-30 13:50 UTC, Aso2101122 commented on src/main/java/com/example/bugbug/service/RecipeServiceImpl.java
> +		   if(!materials.get(i).equals("") && !amounts.get(i).equals("")) {
この分岐でfalseになったときの処理が不明確（片方だけ入力されてた時はユーザー視点ではなにもレスポンスがなく、入力が終わってしまう）というのと、入力チェックは相関チェックのバリデーションクラスを作ってやった方がいいかも

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/repository/TagRepository.java
> +    boolean existsByName(String name);
リポジトリのメソッドはコメントが欲しい

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/repository/RecipeRepository.java
> +    int getId();
この一番大きいレシピIDを取得するメソッドはどこで使ってるんだっけ？

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/entity/RecipeProcedure.java
> +	private String context;
ここのDBのレコード名contextじゃなくて、言いたかったのはcontentやった、、、間違って教えたすまん、、、

2022-11-30 13:50 UTC, soudai531 commented on src/main/java/com/example/bugbug/entity/Recipe.java
>      private String explan;
explanっていう単語は動詞で「説明」ではなく「説明する」っていう意味やったから、
意味的にはexplanationが正しかったかも。
DBは後日変えるからとりあえず、@Columnで今のレコード名つけておいて

2022-11-30 13:52 UTC, soudai531 commented on src/main/java/com/example/bugbug/controller/RecipeController.java
> +		return "index";
htmlを返すのではなく、リダイレクトでお願いします。

2022-12-02 02:23 UTC, Aso2001025 commented on src/main/java/com/example/bugbug/entity/Recipe.java
>      private String explan;
変更ずみ

2022-12-02 02:24 UTC, Aso2001025 commented on src/main/java/com/example/bugbug/entity/RecipeProcedure.java
> +	private String context;
変更ずみ

2022-12-02 02:25 UTC, Aso2001025 commented on src/main/java/com/example/bugbug/repository/RecipeRepository.java
> +    int getId();
削除ずみ

2022-12-02 02:29 UTC, Aso2001025 commented on src/main/java/com/example/bugbug/repository/TagRepository.java
> +    boolean existsByName(String name);
記述ずみ

2022-12-02 02:31 UTC, Aso2001025 commented on src/main/java/com/example/bugbug/form/RecipeRegisterForm.java
> +	private List<MultipartFile> datail_images;
修正ずみ

2022-12-02 02:33 UTC, Aso2001025 commented on src/main/java/com/example/bugbug/form/RecipeRegisterForm.java
> +	private String explan;
修正済み

2022-12-12 01:39 UTC, Aso2101122 commented on src/main/java/com/example/bugbug/controller/RecipeController.java
> +		return "index";
修正済み

2022-12-12 01:44 UTC, Aso2101122 commented on src/main/java/com/example/bugbug/service/TagServiceImpl.java
> +    //IDの取得
修正済み

2022-12-12 01:46 UTC, Aso2101122 commented on src/main/java/com/example/bugbug/service/RecipeServiceImpl.java
> +		   if(!materials.get(i).equals("") && !amounts.get(i).equals("")) {
Todoコメントとして残しておく

2022-12-12 03:30 UTC, Aso2101122 approved these changes
動作確認＆レビュー完了

2022-12-12 03:31 UTC, merged