Feature #26 create password updatepage
Aso2101122/bugbug pull request #59
Opened 2022-12-06 01:40 UTC by Aso2001024

## チケット(issue)へのリンク

* https://github.com/Aso2101122/bugbug/issues/#26

## やったこと
パスワード変更画面の作成

## できるようになること（ユーザ目線）
パスワードが変更できる

2022-12-06 13:54 UTC, Aso2101122 commented
プルリクエストのマージ先のブランチがdevelopじゃなくてmastarになってたから気を付けて！！！

2022-12-08 03:31 UTC, Aso2001011 commented on src/main/resources/templates/passwordCheck.html
> +</body>
不要なタグがあります

2022-12-08 03:31 UTC, Aso2001011 commented on src/main/resources/templates/passwordCheck.html
> +    <title>passwordCheck</title>
タイトルは
ページ名 : bugbug
に変更してください

2022-12-08 03:31 UTC, Aso2001011 commented on src/main/resources/templates/passwordUpdate.html
> +    <title>passwordUpdate</title>
タイトルは
ページ名 : bugbug
に変更してください

2022-12-08 14:06 UTC, Aso2101122 commented on src/main/resources/static/css/passwordUpdate.css
> +}
丸みだけ別のクラスにしているのにはなんか理由があったりする？

2022-12-08 14:10 UTC, soudai531 commented on src/main/resources/templates/passwordUpdate.html
> +        <h3 class="title">パスワードの変更</h3>
「h〇」タグ（h1やh2）を内容のではなく、文字の大きさを変えるための使いかたは好ましくないので、
見出しとなる部分は必ずh1から始めて、見た目の部分はcssで調整してください。

2022-12-08 14:12 UTC, Aso2101122 commented on src/main/resources/templates/passwordUpdate.html
> +            <p class="text required">パスワード</p><br>
pタグは段落があるような文章に使うのでこういう部分はなるべくspanタグを使うと良い

2022-12-09 02:33 UTC, Aso2001024 commented on src/main/resources/templates/passwordCheck.html
> +</body>
変更しました

2022-12-09 02:34 UTC, Aso2001024 commented on src/main/resources/templates/passwordCheck.html
> +    <title>passwordCheck</title>
変更しました

2022-12-09 02:35 UTC, Aso2001024 commented on src/main/resources/templates/passwordUpdate.html
> +    <title>passwordUpdate</title>
変更しました

2022-12-09 03:08 UTC, Aso2001024 commented on src/main/resources/static/css/passwordUpdate.css
> +}
変更しました

2022-12-09 03:09 UTC, Aso2001024 commented on src/main/resources/templates/passwordUpdate.html
> +            <p class="text required">パスワード</p><br>
変更しました

2022-12-09 12:45 UTC, Aso2101122 commented on src/main/resources/static/css/passwordCheck.css
> +}
空白行を無くしてください！

2022-12-09 12:45 UTC, Aso2101122 commented on src/main/resources/static/css/passwordUpdate.css
> +
こちらも空白行をなくしてください

2022-12-13 00:44 UTC, Aso2001011 requested changes

2022-12-13 00:44 UTC, Aso2001011 commented on src/main/resources/templates/passwordUpdate.html
> +            <h:outputText styleClass="required" />
消して大丈夫

2022-12-13 00:44 UTC, Aso2001011 commented on src/main/resources/templates/passwordUpdate.html
> +    <title>passwordUpdate</title>
ここも変更できてない

2022-12-13 00:44 UTC, Aso2001011 commented on src/main/resources/templates/passwordCheck.html
> +    <title>passwordCheck</title>
また変更できてない
ページ名は日本語統一で
このページなら
「パスワード確認 : bugbug」

2022-12-13 00:44 UTC, Aso2001011 commented on src/main/resources/static/css/passwordUpdate.css
> +a.no-acaunt {
ここもタグがないから消していい

2022-12-13 00:44 UTC, Aso2001011 commented on src/main/resources/static/css/passwordCheck.css
> +a.no-acaunt {
htmlの方にno-acountのタグがないから消していい

2022-12-13 00:55 UTC, Aso2001011 approved these changes

2022-12-13 00:55 UTC, merged